### ISSUE TITLE
Implement POST /api/stable/auth/login

### ISSUE THREAD

**Issue by blackandred** [riotkit-org/backup-repository#167]
- The endpoint should look for user data in `kind: BackupUser`, additionally fetch hashed password from `kind: Secret` if used.
- Generated JWT token should be hashed with sha256 and stored as a `GrantedAccess` to give possibility of auditing what tokens were already granted, and to revoke such token

**Example `GrantedAccess`**

```yaml
---
apiVersion: backups.riotkit.org/v1alpha1
kind: GrantedAccess
metadata:
    # hash of the JWT
    name: 39671096ba800ca9b238c7c01b053fa0d5d09ca3151e050d148ddfffaefa9466ceba75d47c2098a0f72110aea4deeb24f6cd1b31f27e27aa6fe7b82dad956049
spec:
    expiresAt: "2022-01-01 08:00"
    active: true
    description: "Temporary token for single file upload"
    requesterIP: "1.2.3.4"
```

**Example BackupUser**

```yaml
---
apiVersion: backups.riotkit.org/v1alpha1
kind: BackupUser
metadata:
    name: admin
spec:
    email: riotkit@riseup.net
    deactivated: false
    organization: "Riotkit"
    about: "System administrator"
    password: "hashed"
    passwordFromRef:  # alternatively, fetch from `kind: Secret`
        name: backup-repository-passwords
        entry: admin
    restrictByIP:
        - 1.2.3.4
    roles:
        - collectionManager
        - usersManager
        - systemAdmin
```

**Example Secret**

*Notice: The secret could be SHARED with multiple users*

```yaml
---
apiVersion: v1
kind: Secret
metadata:
    name: backup-repository-passwords
type: Opaque
data:
    # admin: admin
    # to generate: `backup-repository --encode-password "admin"
    admin: "JGFyZ29uMmlkJHY9MTkkbT02NTUzNix0PTEscD00JHpuVy9IT2Y4Q3RkdStvNSttYlR2REE9PSRaZlVpRGl2QWV2T2RZNndKYWJBb0FQdmM1a1hsemxDNkg2OFY2dGVmNUY0PQ=="

```
